services:

  postgres:
    image: postgis/postgis:16-3.4

    container_name: survey-monitor-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  app:
    build: .

    container_name: survey-monitor-app

    env_file:
      - .env

    depends_on:
      - postgres

    volumes:
      - .:/app

    command: python -m src.main

volumes:
  postgres_data: