version: "3.9"

services:

  app:

    build: .

    container_name: survey-monitor-app

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - postgres

    command: python src/main.py

  postgres:

    image: postgres:16

    container_name: survey-monitor-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: survey_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: