"""
Alert ORM Model
"""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import BigInteger
from sqlalchemy import DateTime
from sqlalchemy import Enum
from sqlalchemy import ForeignKey
from sqlalchemy import String
from sqlalchemy import Text
from sqlalchemy import func
from sqlalchemy.orm import Mapped
from sqlalchemy.orm import mapped_column
from sqlalchemy.orm import relationship

from src.database.base import Base
from src.utils.enums import AlertPriority
from src.utils.enums import AlertStatus
from src.utils.enums import AlertType

if TYPE_CHECKING:
    from src.database.models.project import Project
    from src.database.models.survey_response import SurveyResponse


class Alert(Base):
    """
    Stores alerts generated by rule-based,
    statistical, or machine learning checks.
    """

    __tablename__ = "alerts"

    alert_id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
    )

    response_id: Mapped[int | None] = mapped_column(
        ForeignKey(
            "survey_responses.response_id",
            ondelete="SET NULL",
        ),
        nullable=True,
    )

    project_id: Mapped[int] = mapped_column(
        ForeignKey(
            "projects.project_id",
            ondelete="CASCADE",
        ),
        nullable=False,
    )

    alert_type: Mapped[AlertType] = mapped_column(
        Enum(AlertType),
        nullable=False,
    )

    priority: Mapped[AlertPriority] = mapped_column(
        Enum(AlertPriority),
        nullable=False,
    )

    status: Mapped[AlertStatus] = mapped_column(
        Enum(AlertStatus),
        default=AlertStatus.OPEN,
        nullable=False,
    )

    message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )

    resolved_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
    )

    project: Mapped["Project"] = relationship(
        back_populates="alerts",
    )

    response: Mapped["SurveyResponse | None"] = relationship(
        back_populates="alerts",
    )

    def __repr__(self) -> str:
        return (
            f"<Alert("
            f"id={self.alert_id}, "
            f"type='{self.alert_type}', "
            f"priority='{self.priority}', "
            f"status='{self.status}'"
            f")>"
        )